brew 'bat'
brew 'bitwarden-cli'
brew 'coreutils'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'go'
brew 'jq'
brew 'make'
brew 'mas'
brew 'neovim'
brew 'netcat'
brew 'nmap'
brew 'rg'
brew 'shellcheck'
brew 'stylua'
brew 'telnet'
brew 'texlive'
brew 'tmux'
brew 'uv'
brew 'vim'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

cask 'brave-browser'
cask 'docker'
cask 'ghostty'
cask 'macfuse'
cask 'mullvad-browser'
cask 'postico'
cask 'pycharm'
cask 'raycast'
cask 'tailscale'
cask 'utm'
cask 'veracrypt'

mas 'Bitwarden', id: 1352778147
