# https://github.com/driesvints/dotfiles/blob/main/Brewfile
tap 'homebrew/cask'

# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
brew 'openssl'
brew 'readline'
brew 'sqlite3'
brew 'xz'
brew 'zlib'
brew 'tcl-tk'

# Binaries
brew 'bat'
brew 'coreutils'
brew 'fd'
brew 'fzf'
brew 'htop'
brew 'gcc'
brew 'git'
brew 'jq'
brew 'make'
brew 'mas'
brew 'neofetch'
brew 'neovim'
brew 'netcat'
brew 'ngrok'
brew 'nmap'
brew 'go'
brew 'pyenv'
brew 'rg'
brew 'shpotify'
brew 'texlive'
brew 'tree'
brew 'vim'
brew 'zoxide'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Apps
cask 'brave-browser'
cask 'docker'
cask 'iterm2'
cask 'postico'
cask 'protonvpn'
cask 'pycharm'
cask 'raspberry-pi-imager'
cask 'spotify'
cask 'utm'
cask 'veracrypt'
cask 'visual-studio-code'

mas 'Xcode', id: 497799835
mas 'Bitwarden', id: 1352778147
mas 'Raivo OTP', id: 1498497896
mas 'WireGuard', id: 1451685025
