#!/usr/bin/env python3

import os
import base64
from urllib.request import Request, urlopen
from urllib.parse import urlencode
import json
import sys

def get_access_token():
    credentials = {}
    # read the same config file as shpotify (https://github.com/hnarayanan/shpotify)
    with open(f"{os.getenv('HOME')}/.shpotify.cfg", "r") as credentials_file:
        for line in credentials_file:
            key, val = line.strip().split("=")
            credentials[key] = val.strip("'").strip('"')

    client_id, client_secret = credentials["CLIENT_ID"], credentials["CLIENT_SECRET"]

    spotify_credentials = base64.b64encode(f"{client_id}:{client_secret}".encode('ascii'))

    req = Request('https://accounts.spotify.com/api/token', method="POST")
    req.add_header('Authorization', f'Basic {spotify_credentials.decode("ascii")}')

    data = urlencode({'grant_type': 'client_credentials'}).encode()

    with urlopen(req, data=data) as resp:
        access_token = json.loads(resp.read().decode())['access_token']

    return access_token


access_token = get_access_token()

query = sys.argv[1]

req = Request(f'https://api.spotify.com/v1/search?type=track&q={query}&limit=50')
req.add_header('Authorization', f'Bearer {access_token}')
req.add_header('Content-Type', 'application/json')

with urlopen(req) as resp:
    response_json = json.loads(resp.read())

tracks = response_json.get('tracks', {}).get('items', [])
for track in tracks:
    print(f"{track['name']} - {track['artists'][0]['name']} - {track['uri'].removeprefix('spotify:track:')}")
